package com.causa.config;

import com.fasterxml.jackson.core.json.JsonReadFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.quarkus.jackson.ObjectMapperCustomizer;
import jakarta.inject.Singleton;

/**
 * Jackson Configuration Customizer
 *
 * <p>Customizes the application-wide Jackson {@link ObjectMapper} managed by Quarkus.
 * Enables {@link JsonReadFeature#ALLOW_UNESCAPED_CONTROL_CHARS} so that JSON payloads
 * containing literal unquoted/unescaped control characters (such as raw newlines inside
 * multi-line text generated by LLM providers like IBM BOB) can be parsed cleanly without
 * throwing {@code JsonParseException}.
 */
@Singleton
public class JacksonConfiguration implements ObjectMapperCustomizer {

    @Override
    public void customize(ObjectMapper objectMapper) {
        objectMapper.enable(JsonReadFeature.ALLOW_UNESCAPED_CONTROL_CHARS.mappedFeature());
    }
}
